# Generated by Django 3.2.15 on 2022-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
